apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https-redirect
  template:
    metadata:
      labels:
        app: nginx-https-redirect
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-https-redirect
