name: Build and push Docker image

on:
  push:
    branches: [ "feature/2.0.1-custom" ]

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build the Docker image
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: us-east1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: us-east1-docker.pkg.dev/apache-superset-378504/custom-superset/custom-supserset:latest